global:
  scrape_interval: 10s

scrape_configs:
  - job_name: auth
    static_configs:
      - targets: ["auth:8000"]
  - job_name: core
    static_configs:
      - targets: ["core:8000"]
  - job_name: report
    static_configs:
      - targets: ["report:8000"]
